// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExhxKA7noi55mR_al5uXtOIK_aMubF14',
    appId: '1:1016227013753:web:9d081c01262825a7dea0a8',
    messagingSenderId: '1016227013753',
    projectId: 'expensetracker-6740f',
    authDomain: 'expensetracker-6740f.firebaseapp.com',
    storageBucket: 'expensetracker-6740f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRO1NoI-degpIGP970Wso74f10SGTVog',
    appId: '1:1016227013753:android:46695eecbd418f24dea0a8',
    messagingSenderId: '1016227013753',
    projectId: 'expensetracker-6740f',
    storageBucket: 'expensetracker-6740f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUsUjbmYVIO5DCxQ2bQtNHjLJNavDW7zw',
    appId: '1:1016227013753:ios:4c03d460e74622fedea0a8',
    messagingSenderId: '1016227013753',
    projectId: 'expensetracker-6740f',
    storageBucket: 'expensetracker-6740f.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUsUjbmYVIO5DCxQ2bQtNHjLJNavDW7zw',
    appId: '1:1016227013753:ios:bf8f2776dc46f383dea0a8',
    messagingSenderId: '1016227013753',
    projectId: 'expensetracker-6740f',
    storageBucket: 'expensetracker-6740f.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
